### ISSUE TITLE
Some notes abot DESCRIPTION

### ISSUE THREAD

**Issue by timcdlucas** [aknandi/disaggregation#1]
I know this is first stab. So... hope this isn't annoying to start pointing things out...

But thought I might as well note them when I see them.

Couple of things to kinda copy over from this DESCRIPTION:
https://github.com/timcdlucas/INLAutils/blob/master/DESCRIPTION

First I think they request authors done like in there now. And it's good to link Orcid IDs if you have one.

```
Authors@R: c(
    person("Anita", "Nandi", email = "drgdrg", role = "aut", comment = c(ORCID = "3443453453")),
    person("Tim", "Lucas", email =  "timcdlucas@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-4694-8107")),
    person("Andre", "Python", email = "python.andre@gmail.com", role = "aut", comment = c(ORCID = "0000-0001-8094-7226"))
)
```

or something. Plus Rohan.

Then looking forward to both Travis CI and CRAN, INLA is a bit of pain. Has to go in Suggests rather than Imports (because otherwise CRAN will try to download it from CRAN) and need to add a line saying where it can be got.

`Additional_repositories: https://inla.r-inla-download.org/R/stable`.

Think that's all I've got for now.

**Comment by aknandi** [comment]
Added authors in commit https://github.com/aknandi/disaggregation/commit/d7f9b60499af2020e4800df8fa8e38cc17bc51f0 

Added "Additional_repositories" and INLA in "Suggests" in DESCRIPTION file and linked repo to Travis CI in commit https://github.com/aknandi/disaggregation/commit/e8b692eb18d1f1e3bc44f6a3915f61f03cb692b4
