### ISSUE TITLE
More info about default mesh parameters

### ISSUE THREAD

**Issue by VirginiaMorera** [aknandi/disaggregation#63]
Not really an issue or enhancement but it might be a good idea to add a warning somewhere when people leave the mesh parameters to be specified by default, that the units are degrees. I was trying to run a quick prelim model with data in a projection in meters, but of course the default parameters which I expected to make a pretty large mesh, because of the change in units, were trying to make a minuscule mesh.

**Comment by timcdlucas** [comment]
Hi,

Yes this is a good point and I'll add it to the documentation.

Tim
