### ISSUE TITLE
R crashes with the disag_model function

### ISSUE THREAD

**Issue by VirginiaMorera** [aknandi/disaggregation#64]
I am trying to run disag_model and immediately makes RStudio crash the moment I run the line (so the issue is not computational power). This happens when running the model with my data, but not with the example data from the workshop, so it seems that there is some kind of issue with it, but can't find it. 

This is my code to create the data object (data projection is in m): 

    data_for_model <- prepare_data(polygon_shapefile =  shapes_sp,
                                   covariate_rasters = covariate_stack,
                                   aggregation_raster = NULL,
                                   response_var = 'CrrctCS',
                                   id_var = 'County_num',
                                   na.action = TRUE, 
                                   mesh.args = list(
                                     max.edge = c(20000, 100000), 
                                     cutoff = 20000, # half the max.edge but not sure why 
                                     offset = c(20000, 20000*10)),
                                   ncores = 4)

And this is what the object looks like

    >summary(data_for_model)
    They data contains 26 polygons and 74934 pixels
    The largest polygon contains 8004 pixels and the smallest polygon contains 875 pixels
    There are 1 covariates
    
    Covariate summary:
       Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      42.17   97.50  127.93  152.37  177.86  842.05 

    >plot(data_for_model)
![image](https://user-images.githubusercontent.com/11058769/176662501-60149d17-ec41-4460-86bc-9e32e936cee1.png)

The following `disag_model()` call makes RStudio crash, and the same thing happens if I leave the priors specified by default

    fitted_model <- disag_model(data = data_for_model,
                                family = 'poisson',
                                link = 'log', 
                                priors = list(priormean_intercept = -4.0,
                                              priorsd_intercept = 2.0,
                                              priormean_slope = 0.0,
                                              priorsd_slope = 0.5,
                                              prior_rho_min = 20000,
                                              prior_rho_prob = 0.1,
                                              prior_sigma_max = 1,
                                              prior_sigma_prob = 0.1,
                                              prior_iideffect_sd_max = 1,
                                              prior_iideffect_sd_prob = 0.1))

If I get the code of the function and run it line by line, the crash happens in the `make_model_object` function, and if I get the code of that and run it line by line, everything seems to work and I can work through the steps and get to the end and obtain a model output that does not look great (it shouldn't, the covar list is just a sample), but seems to have worked: 

    >summary(model_output)
    Likelihood function: poisson 
    Link function: log 
    Model parameters:
                         Estimate Std. Error
    intercept         -4.94353526  1.2352668
    slope             -0.03303373  0.0143124
    iideffect_log_tau  0.18533900  0.7617701
    log_sigma         -0.58900695  1.3117144
    log_rho           10.66287437  1.0111116
    
    Model convergence: 0 (relative convergence (4))
    Negative log likelihood:  -17.0706392726761 

    In sample performance:
          RMSE       MAE   pearson  spearman log_pearson
    1 0.515456 0.3617302 0.9262397 0.8003419   0.8966237

    plot(model_output)
![image](https://user-images.githubusercontent.com/11058769/176664426-40fdcbf2-f588-4315-9f44-2fa02385b579.png)

And the predict function also seems to work. 

    plot(predict(model_output))
![image](https://user-images.githubusercontent.com/11058769/176664672-e1fc2e82-d1af-4201-80ec-2747c40657e6.png)

So, I guess I could just work through the code inside the functions every time and live like that, but any idea why that might be happening? Happy to share the data for tests if needed!

**Comment by VirginiaMorera** [comment]
I was going through the closed issues and I came accross #53 so I've tried with two covariates and it seems to run, so it might be that that is not solved yet??

**Comment by VirginiaMorera** [comment]
Yeah tried with the Github version and the problem disappeared, sorry about that, and thanks for the quick reply!

**Comment by timcdlucas** [comment]
No problem!
