### ISSUE TITLE
Option to plot in sample obs vs pred without iid term

### ISSUE THREAD

**Issue by timcdlucas** [aknandi/disaggregation#68]

**Comment by timcdlucas** [comment]
This is currently done via `report()`. So requires a bit of thought for how to do it. Maybe easiest to alter the .cpp file to report predictions without iid. Otherwise needs to reaggregate etc.

**Comment by simon-smart88** [comment]
Look in `x$opt` or `x$obj` and subtract from exisiting predictions

**Comment by simon-smart88** [comment]
Looking at `predict.R` I found the polygon iid effects can be found here:

```
pars <- x$obj$env$last.par.best
iid_poly <- pars[names(pars) == "iideffect"]
```

I've verified that those are the same values as running `predict_model(iid_effect = TRUE)` and then doing `terra::values(pred$iid)` but subtracting those from the polygon predictions doesn't seem to give the intended result. i.e.

```
plot_data <- plot_disag_model_data(result)
plot_data$data$pred_no_iid <- plot_data$data$pred - iid_poly
```

Using the test data the effect is tiny (black = original, red = minus iid):

![00001c](https://github.com/user-attachments/assets/8566e3c2-c0f3-46b6-b763-af4370cce064)

And using the MDG data, the effect is massive:

![000015](https://github.com/user-attachments/assets/d3a01eb0-7d82-435b-8be3-8666a8cde7ec)

I feel like I must be missing something!

**Comment by simon-smart88** [comment]
divide by the exp(iid)

**Comment by simon-smart88** [comment]
This is the default now for MDG:

![00001e](https://github.com/user-attachments/assets/5bc33ad8-7b84-4dde-9b9a-7605a1a43297)

And with `include_iid = TRUE`:

![000022](https://github.com/user-attachments/assets/998173a8-2fc2-4a3a-8d75-827fa1289f04)

The test data is weird but also works, just that the IID effect is basically everything.

@timcdlucas should be good to close unless you have comments

**Comment by timcdlucas** [comment]
Looks good to me
