### ISSUE TITLE
rgeos and maptools are being depreciated

### ISSUE THREAD

**Issue by timcdlucas** [aknandi/disaggregation#70]
https://r-spatial.org/r/2022/12/14/evolution2.html

Looks like it's time to port over to terra or whatever else. Might be first job for the Wellcome trust post doc.

**Comment by timcdlucas** [comment]
@rsbivand Thanks for all this.

**Comment by rsbivand** [comment]
Only three months remain to keep your package online on CRAN. I can see promising activity on the terra branch, @timcdlucas  please let me know whether I can assist.

**Comment by timcdlucas** [comment]
@rsbivand I'm working on the terra branch but it's difficult to find time.

Can I just confirm that raster and sp aren't being removed this year? Just rgeos, maptools and rgdal? 

In order to make things easy on myself I think I'll just remove those packages (about 2 lines as far as I know) and then go back to the terra branch later.

**Comment by rsbivand** [comment]
Right, only `maptools`, `rgdal` and `rgeos` are being archived on CRAN in October 2023. `sp` and `raster` willcontinue, the former using `sf` in place of retiring packages, the latter `terra` in their place.

**Comment by timcdlucas** [comment]
12ae1b616ea489370b528e907907657f6d361366
8431308d2e5b252f8783235b3f1599f3662cbc35
25219e085677938da3df219da4b5f3658ded20e0

Just to keep things together and because I forgot to reference this issue from the commits.

**Comment by timcdlucas** [comment]
I believe this is now complete. Will be submitting to CRAN soon.

**Comment by rsbivand** [comment]
Thanks, running CMD check on the current repository master HEAD on sp evolution status 2 without the retiring packages on the library path gives this log: 
[00check.log](https://github.com/aknandi/disaggregation/files/12148852/00check.log)

**Comment by timcdlucas** [comment]
Hi @rsbivand as far as I understand this is now totally sorted. New version of disaggregation is on CRAN and doesn't depend on any of the old packages.
https://cran.r-project.org/web/packages/disaggregation/index.html

Full switching to terra from raster is ongoing, but there's no strict time pressure on that yet.

**Comment by rsbivand** [comment]
Yes, thanks!

**Comment by timcdlucas** [comment]
Thank you @rsbivand for corralling us all through it by the way. Sure it's been a large and thankless task.
