### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by Shruthi-Patil** [aknandi/disaggregation#71]
Hi, 
do you have a paper that explains the disaggregation methods ? 

Thanks, 
Shruthi

**Comment by timcdlucas** [comment]
Hi,

This paper describes the package and the method
https://arxiv.org/abs/2001.04847

And this paper describes some of the potential considerations of the method in terms of sample size etc.
https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.9220
